// Generated by CoffeeScript 1.10.0
var app;

app = angular.module('app', []);

app.controller('MainController', function($scope) {
  $scope.count = 0;
  $scope.click = function() {
    return $scope.count += 1;
  };
  return $scope.yell = function() {
    return alert('hello');
  };
});
