// Generated by CoffeeScript 1.10.0
var config, engine;

config = Config.get();

config.fillWindow();

config.toggleStats();

engine = new Engine3D();

Engine3D.scenify(engine, function() {
  Utils.console();
  return Helper.orbitControls(engine);
});

engine.render();
